### ISSUE TITLE
[TODO] Missing Features 1.14

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/PetCollars#1]
- [x] remove collar from pet
- [x] remove pendant from collar
- [x] larger collar with more pendant slots (gold collar)
- [x] JEI recipes for collar crafter

## Remove collar from Pet
Maybe add a plier, that can be used on animals; the collar will drop as item.

## Remove pendant from collar
Collar crafter will uncraft it when a 'crafter'/'full' collar is used

## Larger collar with more pendant slots
I need a new texture for this.
